### ISSUE TITLE
Standard Green + Standard Yellow: Color and ECP Styles

### ISSUE THREAD

**Issue by joseph-fowler** [i7MEDIA/mojoskins#23]
Standard Green is blue as is Standard Yellow, Broken Event Calendar Pro (Month View + Month View Module)

**Comment by Isaac-Hall** [comment]
Fixed Standard Green with https://github.com/i7MEDIA/mojoskins/commit/0993533e45a9c1365cd0cc4ac7d1b09e3937371e
Fixed Standard Yellow with https://github.com/i7MEDIA/mojoskins/commit/b2b07e5296573d091762de216d66bfbd4d820ffa

Event Calendar Pro works fine but looked ugly because the theme.skin was configured wrong. We ship these skins with those settings commented out to prevent errors when pro modules aren't installed. Uncommenting the ECP settings in theme.skin fixes the issue, but we won't do that in the repo.
